# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EditDrinkRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, ingredients: List[str]=None, price: float=None, quantity: int=None, is_active: bool=None):  # noqa: E501
        """EditDrinkRequest - a model defined in Swagger

        :param name: The name of this EditDrinkRequest.  # noqa: E501
        :type name: str
        :param ingredients: The ingredients of this EditDrinkRequest.  # noqa: E501
        :type ingredients: List[str]
        :param price: The price of this EditDrinkRequest.  # noqa: E501
        :type price: float
        :param quantity: The quantity of this EditDrinkRequest.  # noqa: E501
        :type quantity: int
        :param is_active: The is_active of this EditDrinkRequest.  # noqa: E501
        :type is_active: bool
        """
        self.swagger_types = {
            'name': str,
            'ingredients': List[str],
            'price': float,
            'quantity': int,
            'is_active': bool
        }

        self.attribute_map = {
            'name': 'name',
            'ingredients': 'ingredients',
            'price': 'price',
            'quantity': 'quantity',
            'is_active': 'is_active'
        }
        self._name = name
        self._ingredients = ingredients
        self._price = price
        self._quantity = quantity
        self._is_active = is_active

    @classmethod
    def from_dict(cls, dikt) -> 'EditDrinkRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditDrinkRequest of this EditDrinkRequest.  # noqa: E501
        :rtype: EditDrinkRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this EditDrinkRequest.


        :return: The name of this EditDrinkRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EditDrinkRequest.


        :param name: The name of this EditDrinkRequest.
        :type name: str
        """

        self._name = name

    @property
    def ingredients(self) -> List[str]:
        """Gets the ingredients of this EditDrinkRequest.


        :return: The ingredients of this EditDrinkRequest.
        :rtype: List[str]
        """
        return self._ingredients

    @ingredients.setter
    def ingredients(self, ingredients: List[str]):
        """Sets the ingredients of this EditDrinkRequest.


        :param ingredients: The ingredients of this EditDrinkRequest.
        :type ingredients: List[str]
        """

        self._ingredients = ingredients

    @property
    def price(self) -> float:
        """Gets the price of this EditDrinkRequest.


        :return: The price of this EditDrinkRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this EditDrinkRequest.


        :param price: The price of this EditDrinkRequest.
        :type price: float
        """

        self._price = price

    @property
    def quantity(self) -> int:
        """Gets the quantity of this EditDrinkRequest.


        :return: The quantity of this EditDrinkRequest.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this EditDrinkRequest.


        :param quantity: The quantity of this EditDrinkRequest.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def is_active(self) -> bool:
        """Gets the is_active of this EditDrinkRequest.


        :return: The is_active of this EditDrinkRequest.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active: bool):
        """Sets the is_active of this EditDrinkRequest.


        :param is_active: The is_active of this EditDrinkRequest.
        :type is_active: bool
        """

        self._is_active = is_active
