# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PurchaseDrinkRequestInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, quantity: int=None):  # noqa: E501
        """PurchaseDrinkRequestInner - a model defined in Swagger

        :param name: The name of this PurchaseDrinkRequestInner.  # noqa: E501
        :type name: str
        :param quantity: The quantity of this PurchaseDrinkRequestInner.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'name': str,
            'quantity': int
        }

        self.attribute_map = {
            'name': 'name',
            'quantity': 'quantity'
        }
        self._name = name
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'PurchaseDrinkRequestInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PurchaseDrinkRequest_inner of this PurchaseDrinkRequestInner.  # noqa: E501
        :rtype: PurchaseDrinkRequestInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this PurchaseDrinkRequestInner.


        :return: The name of this PurchaseDrinkRequestInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PurchaseDrinkRequestInner.


        :param name: The name of this PurchaseDrinkRequestInner.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def quantity(self) -> int:
        """Gets the quantity of this PurchaseDrinkRequestInner.


        :return: The quantity of this PurchaseDrinkRequestInner.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this PurchaseDrinkRequestInner.


        :param quantity: The quantity of this PurchaseDrinkRequestInner.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
